#!/bin/bash
#------------------------------------------------------------------------------
# Albert Akhriev, albert_akhriev@ie.ibm.com
# IBM Research Dublin (c)
#------------------------------------------------------------------------------

echo "Copying the project from the virtual machine ..."

DESTIN="${VM}:/home/${USER}/work/"

rsync -arv \
--exclude 'bin' --exclude 'output' --exclude 'build_debug' --exclude 'build_release' \
--exclude '*.jpg' --exclude '*.pdf' --exclude 'verdandi*' --exclude 'build' \
--exclude '*.tgz' --exclude '*.zip' --exclude '*gdb.sh' --exclude '.git*' \
--exclude 'Results' --exclude 'tags' --exclude "octave-workspace" \
--exclude '*.*.swp' --exclude '*~' --exclude '*.swo' --exclude '*.log' \
--exclude 'documentation'  --exclude 'doc' --exclude 'experimental' \
--exclude '__pycache__' \
${DESTIN}/allscale_amdados ../

echo ""
echo ""
echo ""

